<?php 

class CancelRequest{
	const ID = "ID";
	const USER_ID = "USER_ID";
	const PERSONEL_ID = "PERSONEL_ID";
	const CREATION_DATE = "CREATION_DATE";
	const COMPLETE_DATE = "COMPLETE_DATE";
	const SOZLESME = "SOZLESME";
	const POLICY_NUMBER = "POLICY_NUMBER";
	const COMPANY_ID = "COMPANY_ID";
	const POLICY_TYPE = "POLICY_TYPE";
	const EK_BILGI = "EK_BILGI";
	const STATUS = "STATUS";
	const BRANCH_NAME = "BRANCH_NAME";
	const PERSONEL_NAME = "PERSONEL_NAME";
	const COMPANY_NAME = "COMPANY_NAME";
}

?>