<?php

class Policy{
	const REQUEST_ID = "REQUEST_ID";
	const REQUEST_DATE = "REQUEST_DATE";
	const POLICY_TYPE = "POLICY_TYPE";
	const BRANCH_ID = "BRANCH_ID";
	const PLAKA = "PLAKA";
	const TCKN = "TCKN";
	const VERGI = "VERGI";
	const BELGE = "BELGE";
	const ASBIS = "ASBIS";
	const EK_BILGI = "EK_BILGI";
	const OFFER_ID = "OFFER_ID";
	const PERSONEL_ID = "PERSONEL_ID";
	const PRIM = "PRIM";
	const KOMISYON = "KOMISYON";
	const PROD_KOMISYON = "PROD_KOMISYON";
	const OFFER_DATE = "OFFER_DATE";
	const PERSONEL_NAME = "PERSONEL_NAME";
	const BRANCH_NAME = "BRANCH_NAME";
	const COMPANY_NAME = "COMPANY_NAME";
	const CARD_ID = "CARD_ID";
	const CARD_NAME = "CARD_NAME";
	const CARD_NO = "CARD_NO";
	const EXPIRE_DATE = "EXPIRE_DATE";
	const CVC_CODE = "CVC_CODE";
	const POLICY_REQ_DATE = "POLICY_REQ_DATE";
	const POLICY_ID = "POLICY_ID";
	const POLICY_COMPLETE_PERSONEL = "POLICY_COMPLETE_PERSONEL";
	const POLICY_COMPLETE_DATE = "POLICY_COMPLETE_DATE";
	const POLICY_PATH = "POLICY_PATH";
	const MAKBUZ_PATH = "MAKBUZ_PATH";
}

?>