<?php

class Recon{
	const TAKIP_NO = "TAKIP_NO";
	const TANZIM_TARIHI = "TANZIM_TARIHI";
	const URETIM_KANALI = "URETIM_KANALI";
	const MUSTERI_TIPI = "MUSTERI_TIPI";
	const YENI_TECDIT = "YENI_TECDIT";
	const POLICE_NO = "POLICE_NO";
	const ZEYIL_NO = "ZEYIL_NO";
	const MUSTERI_ADI = "MUSTERI_ADI";
	const TCKN = "TCKN";
	const VERGI_NO = "VERGI_NO";
	const EK_BILGI = "EK_BILGI";
	const BOLGE = "BOLGE";
	const BAGLI = "BAGLI";
	const PRODUKTOR = "PRODUKTOR";
	const PRODUKTOR_ID = "PRODUKTOR_ID";
	const TEKNIKCI_ID = "TEKNIKCI_ID";
	const TEKNIKCI_ID_POLICY = "TEKNIKCI_ID_POLICY";
	const BASLANGIC_TARIHI = "BASLANGIC_TARIHI";
	const BITIS_TARIHI = "BITIS_TARIHI";
	const SIRKET = "SIRKET";
	const SIRKET_ID = "SIRKET_ID";
	const POLICE_TURU = "POLICE_TURU";
	const PARA_BIRIMI = "PARA_BIRIMI";
	const BRUT = "BRUT";
	const NET = "NET";
	const KOMISYON = "KOMISYON";
	const TAHSILAT_DURUMU = "TAHSILAT_DURUMU";
	const SIRKET_TAHSILAT_DURUMU = "SIRKET_TAHSILAT_DURUMU";
	const ACIKLAMA = "ACIKLAMA";
	const HERO_KOMISYON = "HERO_KOMISYON";
	const BOLGE_KOMISYON = "BOLGE_KOMISYON";
	const SUBE_KOMISYON = "SUBE_KOMISYON";
	const BAGLI_KOMISYON = "BAGLI_KOMISYON";
	const MUSTERIYE_IADE = "MUSTERIYE_IADE";
	const PROD_KOMISYON = "PROD_KOMISYON";
	const MERKEZ = "MERKEZ";
}

?>