<?php

class ReconPolicy{
	const POLICY_ID = "POLICY_ID";
	const POLICY_COMPLETE_DATE = "POLICY_COMPLETE_DATE";
	const POLICY_NUMBER = "POLICY_NUMBER";
	const TCKN = "TCKN";
	const VERGI = "VERGI";
	const EK_BILGI = "EK_BILGI";
	const BRANCH_NAME = "BRANCH_NAME";
	const BRANCH_ID = "BRANCH_ID";
	const PERSONEL_ID = "PERSONEL_ID";
	const PERSONEL_ID_POLICY = "PERSONEL_ID_POLICY";
	const COMPANY_NAME = "COMPANY_NAME";
	const COMPANY_ID = "COMPANY_ID";
	const POLICY_TYPE = "POLICY_TYPE";
	const PRIM = "PRIM";
	const KOMISYON = "KOMISYON";
	const PROD_KOMISYON = "PROD_KOMISYON";
	const KAYNAK = "KAYNAK";
	const URETIM_KANALI = "URETIM_KANALI";
	const UST_KOMISYON = "UST_KOMISYON";
	const BAGLI_KOMISYON = "BAGLI_KOMISYON";
	const UST_ACENTE = "UST_ACENTE";
	const BAGLI_ACENTE = "BAGLI_ACENTE";
}

?>